// Türkiye İller ve İlçeler Verisi
export interface Il {
  id: number
  name: string
  plaka: number
}

export interface Ilce {
  id: number
  name: string
  ilId: number
}

export const iller: Il[] = [
  { id: 1, name: 'Adana', plaka: 1 },
  { id: 2, name: 'Adıyaman', plaka: 2 },
  { id: 3, name: 'Afyonkarahisar', plaka: 3 },
  { id: 4, name: 'Ağrı', plaka: 4 },
  { id: 5, name: 'Amasya', plaka: 5 },
  { id: 6, name: 'Ankara', plaka: 6 },
  { id: 7, name: 'Antalya', plaka: 7 },
  { id: 8, name: 'Artvin', plaka: 8 },
  { id: 9, name: 'Aydın', plaka: 9 },
  { id: 10, name: 'Balıkesir', plaka: 10 },
  { id: 11, name: 'Bilecik', plaka: 11 },
  { id: 12, name: 'Bingöl', plaka: 12 },
  { id: 13, name: 'Bitlis', plaka: 13 },
  { id: 14, name: 'Bolu', plaka: 14 },
  { id: 15, name: 'Burdur', plaka: 15 },
  { id: 16, name: 'Bursa', plaka: 16 },
  { id: 17, name: 'Çanakkale', plaka: 17 },
  { id: 18, name: 'Çankırı', plaka: 18 },
  { id: 19, name: 'Çorum', plaka: 19 },
  { id: 20, name: 'Denizli', plaka: 20 },
  { id: 21, name: 'Diyarbakır', plaka: 21 },
  { id: 22, name: 'Edirne', plaka: 22 },
  { id: 23, name: 'Elazığ', plaka: 23 },
  { id: 24, name: 'Erzincan', plaka: 24 },
  { id: 25, name: 'Erzurum', plaka: 25 },
  { id: 26, name: 'Eskişehir', plaka: 26 },
  { id: 27, name: 'Gaziantep', plaka: 27 },
  { id: 28, name: 'Giresun', plaka: 28 },
  { id: 29, name: 'Gümüşhane', plaka: 29 },
  { id: 30, name: 'Hakkari', plaka: 30 },
  { id: 31, name: 'Hatay', plaka: 31 },
  { id: 32, name: 'Isparta', plaka: 32 },
  { id: 33, name: 'Mersin', plaka: 33 },
  { id: 34, name: 'İstanbul', plaka: 34 },
  { id: 35, name: 'İzmir', plaka: 35 },
  { id: 36, name: 'Kars', plaka: 36 },
  { id: 37, name: 'Kastamonu', plaka: 37 },
  { id: 38, name: 'Kayseri', plaka: 38 },
  { id: 39, name: 'Kırklareli', plaka: 39 },
  { id: 40, name: 'Kırşehir', plaka: 40 },
  { id: 41, name: 'Kocaeli', plaka: 41 },
  { id: 42, name: 'Konya', plaka: 42 },
  { id: 43, name: 'Kütahya', plaka: 43 },
  { id: 44, name: 'Malatya', plaka: 44 },
  { id: 45, name: 'Manisa', plaka: 45 },
  { id: 46, name: 'Kahramanmaraş', plaka: 46 },
  { id: 47, name: 'Mardin', plaka: 47 },
  { id: 48, name: 'Muğla', plaka: 48 },
  { id: 49, name: 'Muş', plaka: 49 },
  { id: 50, name: 'Nevşehir', plaka: 50 },
  { id: 51, name: 'Niğde', plaka: 51 },
  { id: 52, name: 'Ordu', plaka: 52 },
  { id: 53, name: 'Rize', plaka: 53 },
  { id: 54, name: 'Sakarya', plaka: 54 },
  { id: 55, name: 'Samsun', plaka: 55 },
  { id: 56, name: 'Siirt', plaka: 56 },
  { id: 57, name: 'Sinop', plaka: 57 },
  { id: 58, name: 'Sivas', plaka: 58 },
  { id: 59, name: 'Tekirdağ', plaka: 59 },
  { id: 60, name: 'Tokat', plaka: 60 },
  { id: 61, name: 'Trabzon', plaka: 61 },
  { id: 62, name: 'Tunceli', plaka: 62 },
  { id: 63, name: 'Şanlıurfa', plaka: 63 },
  { id: 64, name: 'Uşak', plaka: 64 },
  { id: 65, name: 'Van', plaka: 65 },
  { id: 66, name: 'Yozgat', plaka: 66 },
  { id: 67, name: 'Zonguldak', plaka: 67 },
  { id: 68, name: 'Aksaray', plaka: 68 },
  { id: 69, name: 'Bayburt', plaka: 69 },
  { id: 70, name: 'Karaman', plaka: 70 },
  { id: 71, name: 'Kırıkkale', plaka: 71 },
  { id: 72, name: 'Batman', plaka: 72 },
  { id: 73, name: 'Şırnak', plaka: 73 },
  { id: 74, name: 'Bartın', plaka: 74 },
  { id: 75, name: 'Ardahan', plaka: 75 },
  { id: 76, name: 'Iğdır', plaka: 76 },
  { id: 77, name: 'Yalova', plaka: 77 },
  { id: 78, name: 'Karabük', plaka: 78 },
  { id: 79, name: 'Kilis', plaka: 79 },
  { id: 80, name: 'Osmaniye', plaka: 80 },
  { id: 81, name: 'Düzce', plaka: 81 },
]

// İlçeler - Her il için örnek ilçeler (tam liste çok uzun olur, önemli ilçeleri ekledim)
export const ilceler: Ilce[] = [
  // İstanbul
  { id: 1, name: 'Adalar', ilId: 34 },
  { id: 2, name: 'Bakırköy', ilId: 34 },
  { id: 3, name: 'Beşiktaş', ilId: 34 },
  { id: 4, name: 'Beykoz', ilId: 34 },
  { id: 5, name: 'Beyoğlu', ilId: 34 },
  { id: 6, name: 'Çatalca', ilId: 34 },
  { id: 7, name: 'Eyüpsultan', ilId: 34 },
  { id: 8, name: 'Fatih', ilId: 34 },
  { id: 9, name: 'Gaziosmanpaşa', ilId: 34 },
  { id: 10, name: 'Kadıköy', ilId: 34 },
  { id: 11, name: 'Kartal', ilId: 34 },
  { id: 12, name: 'Sarıyer', ilId: 34 },
  { id: 13, name: 'Silivri', ilId: 34 },
  { id: 14, name: 'Şişli', ilId: 34 },
  { id: 15, name: 'Üsküdar', ilId: 34 },
  { id: 16, name: 'Zeytinburnu', ilId: 34 },
  { id: 17, name: 'Büyükçekmece', ilId: 34 },
  { id: 18, name: 'Kağıthane', ilId: 34 },
  { id: 19, name: 'Küçükçekmece', ilId: 34 },
  { id: 20, name: 'Pendik', ilId: 34 },
  { id: 21, name: 'Ümraniye', ilId: 34 },
  { id: 22, name: 'Maltepe', ilId: 34 },
  { id: 23, name: 'Sultanbeyli', ilId: 34 },
  { id: 24, name: 'Tuzla', ilId: 34 },
  { id: 25, name: 'Esenler', ilId: 34 },
  { id: 26, name: 'Arnavutköy', ilId: 34 },
  { id: 27, name: 'Ataşehir', ilId: 34 },
  { id: 28, name: 'Bağcılar', ilId: 34 },
  { id: 29, name: 'Bahçelievler', ilId: 34 },
  { id: 30, name: 'Başakşehir', ilId: 34 },
  { id: 31, name: 'Bayrampaşa', ilId: 34 },
  { id: 32, name: 'Beşiktaş', ilId: 34 },
  { id: 33, name: 'Beylikdüzü', ilId: 34 },
  { id: 34, name: 'Beyoğlu', ilId: 34 },
  { id: 35, name: 'Çekmeköy', ilId: 34 },
  { id: 36, name: 'Esenyurt', ilId: 34 },
  { id: 37, name: 'Güngören', ilId: 34 },
  { id: 38, name: 'Sancaktepe', ilId: 34 },
  { id: 39, name: 'Sultangazi', ilId: 34 },
  
  // Ankara
  { id: 100, name: 'Altındağ', ilId: 6 },
  { id: 101, name: 'Ayaş', ilId: 6 },
  { id: 102, name: 'Bala', ilId: 6 },
  { id: 103, name: 'Beypazarı', ilId: 6 },
  { id: 104, name: 'Çamlıdere', ilId: 6 },
  { id: 105, name: 'Çankaya', ilId: 6 },
  { id: 106, name: 'Çubuk', ilId: 6 },
  { id: 107, name: 'Elmadağ', ilId: 6 },
  { id: 108, name: 'Güdül', ilId: 6 },
  { id: 109, name: 'Haymana', ilId: 6 },
  { id: 110, name: 'Kalecik', ilId: 6 },
  { id: 111, name: 'Kızılcahamam', ilId: 6 },
  { id: 112, name: 'Nallıhan', ilId: 6 },
  { id: 113, name: 'Polatlı', ilId: 6 },
  { id: 114, name: 'Şereflikoçhisar', ilId: 6 },
  { id: 115, name: 'Yenimahalle', ilId: 6 },
  { id: 116, name: 'Keçiören', ilId: 6 },
  { id: 117, name: 'Mamak', ilId: 6 },
  { id: 118, name: 'Sincan', ilId: 6 },
  { id: 119, name: 'Etimesgut', ilId: 6 },
  { id: 120, name: 'Pursaklar', ilId: 6 },
  { id: 121, name: 'Akyurt', ilId: 6 },
  { id: 122, name: 'Gölbaşı', ilId: 6 },
  { id: 123, name: 'Kazan', ilId: 6 },
  
  // İzmir
  { id: 200, name: 'Aliağa', ilId: 35 },
  { id: 201, name: 'Bayındır', ilId: 35 },
  { id: 202, name: 'Bergama', ilId: 35 },
  { id: 203, name: 'Bornova', ilId: 35 },
  { id: 204, name: 'Çeşme', ilId: 35 },
  { id: 205, name: 'Dikili', ilId: 35 },
  { id: 206, name: 'Foça', ilId: 35 },
  { id: 207, name: 'Karaburun', ilId: 35 },
  { id: 208, name: 'Karşıyaka', ilId: 35 },
  { id: 209, name: 'Kemalpaşa', ilId: 35 },
  { id: 210, name: 'Kınık', ilId: 35 },
  { id: 211, name: 'Kiraz', ilId: 35 },
  { id: 212, name: 'Menemen', ilId: 35 },
  { id: 213, name: 'Ödemiş', ilId: 35 },
  { id: 214, name: 'Seferihisar', ilId: 35 },
  { id: 215, name: 'Selçuk', ilId: 35 },
  { id: 216, name: 'Tire', ilId: 35 },
  { id: 217, name: 'Torbalı', ilId: 35 },
  { id: 218, name: 'Urla', ilId: 35 },
  { id: 219, name: 'Beydağ', ilId: 35 },
  { id: 220, name: 'Buca', ilId: 35 },
  { id: 221, name: 'Konak', ilId: 35 },
  { id: 222, name: 'Menderes', ilId: 35 },
  { id: 223, name: 'Balçova', ilId: 35 },
  { id: 224, name: 'Çiğli', ilId: 35 },
  { id: 225, name: 'Gaziemir', ilId: 35 },
  { id: 226, name: 'Narlıdere', ilId: 35 },
  { id: 227, name: 'Güzelbahçe', ilId: 35 },
  { id: 228, name: 'Bayraklı', ilId: 35 },
  { id: 229, name: 'Karabağlar', ilId: 35 },
  
  // Bursa
  { id: 300, name: 'Osmangazi', ilId: 16 },
  { id: 301, name: 'Nilüfer', ilId: 16 },
  { id: 302, name: 'Yıldırım', ilId: 16 },
  { id: 303, name: 'Mudanya', ilId: 16 },
  { id: 304, name: 'Gemlik', ilId: 16 },
  { id: 305, name: 'Orhangazi', ilId: 16 },
  { id: 306, name: 'İnegöl', ilId: 16 },
  { id: 307, name: 'Mustafakemalpaşa', ilId: 16 },
  { id: 308, name: 'Karacabey', ilId: 16 },
  { id: 309, name: 'Gürsu', ilId: 16 },
  { id: 310, name: 'Kestel', ilId: 16 },
  { id: 311, name: 'Yenişehir', ilId: 16 },
  { id: 312, name: 'Orhaneli', ilId: 16 },
  { id: 313, name: 'Büyükorhan', ilId: 16 },
  { id: 314, name: 'Harmancık', ilId: 16 },
  { id: 315, name: 'İznik', ilId: 16 },
  { id: 316, name: 'Marmara', ilId: 16 },
  
  // Antalya
  { id: 400, name: 'Akseki', ilId: 7 },
  { id: 401, name: 'Alanya', ilId: 7 },
  { id: 402, name: 'Elmalı', ilId: 7 },
  { id: 403, name: 'Finike', ilId: 7 },
  { id: 404, name: 'Gazipaşa', ilId: 7 },
  { id: 405, name: 'Gündoğmuş', ilId: 7 },
  { id: 406, name: 'Kaş', ilId: 7 },
  { id: 407, name: 'Kemer', ilId: 7 },
  { id: 408, name: 'Korkuteli', ilId: 7 },
  { id: 409, name: 'Kumluca', ilId: 7 },
  { id: 410, name: 'Manavgat', ilId: 7 },
  { id: 411, name: 'Serik', ilId: 7 },
  { id: 412, name: 'Muratpaşa', ilId: 7 },
  { id: 413, name: 'Kepez', ilId: 7 },
  { id: 414, name: 'Konyaaltı', ilId: 7 },
  { id: 415, name: 'Döşemealtı', ilId: 7 },
  { id: 416, name: 'Aksu', ilId: 7 },
  { id: 417, name: 'Demre', ilId: 7 },
  { id: 418, name: 'İbradı', ilId: 7 },
  
  // Adana
  { id: 500, name: 'Aladağ', ilId: 1 },
  { id: 501, name: 'Ceyhan', ilId: 1 },
  { id: 502, name: 'Çukurova', ilId: 1 },
  { id: 503, name: 'Feke', ilId: 1 },
  { id: 504, name: 'İmamoğlu', ilId: 1 },
  { id: 505, name: 'Karaisalı', ilId: 1 },
  { id: 506, name: 'Karataş', ilId: 1 },
  { id: 507, name: 'Kozan', ilId: 1 },
  { id: 508, name: 'Pozantı', ilId: 1 },
  { id: 509, name: 'Saimbeyli', ilId: 1 },
  { id: 510, name: 'Sarıçam', ilId: 1 },
  { id: 511, name: 'Seyhan', ilId: 1 },
  { id: 512, name: 'Tufanbeyli', ilId: 1 },
  { id: 513, name: 'Yumurtalık', ilId: 1 },
  { id: 514, name: 'Yüreğir', ilId: 1 },
]

// İl ID'sine göre ilçeleri getir
export function getIlcelerByIlId(ilId: number): Ilce[] {
  return ilceler.filter(ilce => ilce.ilId === ilId)
}

// İl ID'sine göre ili getir
export function getIlById(ilId: number): Il | undefined {
  return iller.find(il => il.id === ilId)
}
